# Automatically generated by configure
prefix=
libdir=  D:/DEV/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/lib/
incdir= D:/DEV/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/include
AR=ar
CC=gcc
RANLIB=ranlib
STRIP=strip
BUILD_SHARED=no
BUILD_STATIC=yes
BUILD_MSVC=
LIBCMD=@echo ignoring lib
WINE=
