# Automatically generated by configure
prefix=/d/DEV/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64
libdir=${prefix}/lib
incdir=${prefix}/include
AR=ar
CC=gcc
RANLIB=ranlib
STRIP=strip
BUILD_SHARED=no
BUILD_STATIC=yes
BUILD_MSVC=
LIBCMD=@echo ignoring lib
WINE=
